# .github/workflows/basic_AT.yml
name: TEMPS basic automated testing

on:
  push:
    branches: 'master'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==24.0
        pip install fdasrsf
        pip install setuptools
        pip install pytest wheel pytest-cov

    - name: Install temps
      run: pip install -e .[explicit]
    # Add this new step to download model files
    - name: Download model files
      run: |
        mkdir -p data/models
        wget -O data/models/modelF_DA.pt https://raw.githubusercontent.com/TEMPS-project/TEMPS/master/data/models/modelF_DA.pt
        wget -O data/models/modelZ_DA.pt https://raw.githubusercontent.com/TEMPS-project/TEMPS/master/data/models/modelZ_DA.pt
    # Run the tests and specify the temporary directory as output_dir
    - name: Run tests
      timeout-minutes: 5
      run: |
        pytest tests/test_temps.py