# .github/workflows/python-tests.yml
name: TEST basic automated testing

on:
  push:
    branches: 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip==24.0
        pip install fdasrsf
        pip install setuptools
        pip install pytest wheel pytest-cov

    - name: Install temps
      run: pip install -e .[explicit]

    # Run the tests and specify the temporary directory as output_dir
    - name: Run tests
      timeout-minutes: 70
      run: |
        pytest tests/test_temps.py